import Head from 'next/head'
import Navbar from '../components/Navbar'
import LoginForm from '../components/LoginForm'

import { Box, Center, Container, Heading, Image, Text } from '@chakra-ui/react'

export default function Login() {
  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Container maxW="2xl" py="10" centerContent>
        <LoginForm />
      </Container>
    </div>
  )
}
